stages:
  - trigger_general

trigger_general_pipeline:
  stage: trigger_general
  trigger:
    project: "entergen/media/representation/general"  # Путь к проекту 'general'
    branch: "test"  # Ветка, для которой будет запускаться пайплайн
    token: "$GENERAL_CI_TRIGGER_TOKEN"  # Токен, который ты получил в репозитории 'general'
    strategy: depend
