stages:
  - trigger_general_pipeline

trigger_general_pipeline:
  stage: trigger_general_pipeline
  script:
    - echo "Triggering the pipeline in the general repository"
  trigger:
    project: "entergen/media/representation/general"  # Путь к репозиторию general
    branch: "test"  # Ветка, в которой должен запуститься пайплайн (можно использовать другую, если нужно)
    token: "$GENERAL_CI_TRIGGER_TOKEN"  # Токен триггера, если требуется
